# -*- coding: utf-8 -*-
"""Lab1_P1_Carrillo_Fuentes_Camila_Keilany.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MV7KVMUlAjTguTsluCjao6tuVxkrZgyX

#Lab 1. Creating a Class, Object, Attributes & Methods
Student: Carrillo Fuentes Camila Keilany Objet-Oriented Programming 4BBIS
---

*In this lab youre gonna explore and create a program that defies a class called "Camera"*
"""

class camera:
  def __init__(self, resolution, brand, vision):
    self.resolution = resolution
    self.brand = brand
    self.vision = vision

  def describe(self):
    print(f"The camera is {self.resolution}")
    print(f"The camera is a {self.brand}")
    print(f"The camera have a {self.vision} vision")

  def move(self):
    print("The camera is moving")

  def record(self):
    print("The camera is recording")
#self: se usa para decirle a python a que objetos pertenecen los atributos
# Crate an instance  using the class table

camara1 = camera("60px", "hikvision", "static")
camara2 = camera("80px", "Dahua", "static")

#we access to the object (intance) "Camara1" to call its data

print(camara1.brand)
print(camara2.resolution)
camara1.move() # Changed from camera.move()
camara2.describe()

#instance "camara"
print(camara2.vision)

"""# Lab 1: Bank Account Class

Create a Python program that models a bank account ussing OOP.
"""

class Laptop:
  def _init_(self, color, material, size):
    self.color = color
    self.material = material
    self.size = size

  def move(self):
    print("The Laptop is Turn off or Turn on")

  def describe(self):
    print(f"This laptop is made with {self.material}",
          f"The color is {self.color} y size:{self.size}")

table1 = Laptop("Grey", "Plastic", "3m3")
table2 = Laptop("Yellow", "Steal", "1x5m")

print(table1.material)
print(table2.color)
table1.move()
table2.describe()

print(table2.material)